name: build Valkey 8.1

on:
  push:
    branches:
      - "releases/*"
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 17
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - macos-14
          - macos-13
        valkey:
          - "8.1.4"
          - "8.1.3"
          - "8.1.2"
          - "8.1.1"
          - "8.1.0"
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: "false"
      - name: build
        shell: bash
        run: ./build-valkey-with-openssl3.sh "$VALKEY_VERSION"
        env:
          VALKEY_VERSION: ${{ matrix.valkey }}

      - name: upload
        run: |
          ACTIONS_VERSION=v$(jq -r .version < "$GITHUB_WORKSPACE/package.json")
          VALKEY_OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          case "$(uname -m)" in
              "x86_64")
                  VALKEY_ARCH="x64"
                  ;;
              "arm64" | "aarch64")
                  VALKEY_ARCH="arm64"
                  ;;
              *)
                  echo "unsupported architecture: $(uname -m)"
                  exit 1
                  ;;
          esac
          mv "$RUNNER_TEMP/valkey-bin.tar.zstd" "$RUNNER_TEMP/valkey-$VALKEY_VERSION-$VALKEY_OS-$VALKEY_ARCH.tar.zstd"
          gh release upload --clobber "$ACTIONS_VERSION" "$RUNNER_TEMP/valkey-$VALKEY_VERSION-$VALKEY_OS-$VALKEY_ARCH.tar.zstd"
        env:
          VALKEY_VERSION: ${{ matrix.valkey }}
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
        with:
          subject-path: ${{ runner.temp }}/*.tar.zstd
