name: build Valkey 9.0

on:
  push:
    branches:
      - "releases/*"
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 17
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - macos-14
          - macos-13
        valkey:
          - "9.0.0"
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: "false"
      - name: build
        shell: bash
        run: ./build-valkey-with-openssl3.sh "$VALKEY_VERSION"
        env:
          VALKEY_VERSION: ${{ matrix.valkey }}

      - name: upload
        run: |
          ACTIONS_VERSION=v$(jq -r .version < "$GITHUB_WORKSPACE/package.json")
          VALKEY_OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          case "$(uname -m)" in
              "x86_64")
                  VALKEY_ARCH="x64"
                  ;;
              "arm64" | "aarch64")
                  VALKEY_ARCH="arm64"
                  ;;
              *)
                  echo "unsupported architecture: $(uname -m)"
                  exit 1
                  ;;
          esac
          mv "$RUNNER_TEMP/valkey-bin.tar.zstd" "$RUNNER_TEMP/valkey-$VALKEY_VERSION-$VALKEY_OS-$VALKEY_ARCH.tar.zstd"
          gh release upload --clobber "$ACTIONS_VERSION" "$RUNNER_TEMP/valkey-$VALKEY_VERSION-$VALKEY_OS-$VALKEY_ARCH.tar.zstd"
        env:
          VALKEY_VERSION: ${{ matrix.valkey }}
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/attest-build-provenance@00014ed6ed5efc5b1ab7f7f34a39eb55d41aa4f8 # v3.1.0
        with:
          subject-path: ${{ runner.temp }}/*.tar.zstd
